ALTER TABLE evaluer
ADD CONSTRAINT FK_EVAL_REC FOREIGN KEY (id_rec) REFERENCES recette(id_rec),
ADD CONSTRAINT FK_EVAL_NOTE FOREIGN KEY (id_note) REFERENCES note(id_note);

ALTER TABLE appartenir
ADD CONSTRAINT FK_APPART_REC FOREIGN KEY (id_rec) REFERENCES recette(id_rec),
ADD CONSTRAINT FK_APPART_CAT FOREIGN KEY (id_cat) REFERENCES categorie(id_cat);

ALTER TABLE comporter
ADD CONSTRAINT FK_COMP_REC FOREIGN KEY (id_rec) REFERENCES recette(id_rec),
ADD CONSTRAINT FK_COMP_INGRE FOREIGN KEY (id_ingre) REFERENCES ingredient(id_ingre);