<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>
<form class="generic-form"  id="order-form" enctype="multipart/form-data">

    <input type="hidden" name="salePrice" value=""/>
    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>
    <fieldset>
        <legend>Ajouter un article</legend>
            <ul>
                <li>
                    <label for="meal">Nom: </label>
                    <select name="meal" id="meal">
                        <?php foreach ($meals as $meal) :?>
                            <option value="<?= $meal['Id']?>"><?= $meal['Name']?></option>
                        <?php endforeach ?>
                    </select>

                    <article id="meal-details" class="meal-details no-left-label">
                        <img src="" alt="Photo du produit" width="240"/>
                        <p></p>
                        <span>Prix: <strong> </strong></span>
                    </article>
                </li>

                <li>
                    <label for="quantity">Quantité: </label>
                    <input type="text" id="quantity" class="quantity" name="quantity" maxlength="2" data-name="Quantité" data-type="positive-integer" data-required/>
                </li>

                <li>
                    <input class="button button-primary no-left-label" type="submit" value="Ajouter">
                </li>
            </ul>
    </fieldset>
    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary"></section>
    </fieldset>

</form>
<ul class="link-list">
    <li>
        <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
        <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
    </li>
</ul>
</ul>
<script src="<?=$wwwUrl?>/js/classes/BasketSession.class.js"></script>
<script src="<?=$wwwUrl?>/js/classes/OrderForm.class.js"></script>