<table class="generic-table" data-order-id="<?=$orderId?>">

    <?php if (empty($basketItems)==true):?>

        <tbody>
            <tr>
                <td class="basket-empty">Votre panier est vide pour le moment !"</td>
            </tr>
        </tbody>

    <?php else :?>

    <thead>
        <tr>
            <th class="number">Quantité</th>
            <th>Nom</th>
            <th class="number">Prix Unitaire</th>
            <th class="number">Prix Total </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach($basketItems as $basketItem):?>
            <tr>
                <td class="number"><?= $basketItem['quantity']?></td>
                <td><?= $basketItem['name']?></td>
                <td class="number"><?= number_format($basketItem['salePrice'],2)?></td>
                <td class="number"><?= number_format($basketItem['quantity']*$basketItem['salePrice'],2)?></td>
                <td> <button class="button button-cancel small" title="supprimer l'article" data-meal-id="<?= $basketItem['mealId']?>"><i class="fa fa-trash"></i></button></td>
            </tr>
        <?php endforeach?>
    </tbody>
    <?php endif?>
</table>

